server:
  port: 7002
dubbo:
  registry:
    address: zookeeper://192.168.1.114:2181
  application:
    name: wash-app
    qos-enable: false
spring:
  jackson:
    default-property-inclusion: non_null
logging:
  level:
   com.wash: debug

  # redis配置，以下有默认配置的也可以使用默认配置
redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 0