server:
  port: 8081
dubbo:
  protocol:
    name: hessian
  application:
    name: third-party-api
  registry:
    address: zookeeper://www.zqazb.xyz:2181
spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB